### PR TITLE
QC exact reformulation for square term

### PR DESCRIPTION
**Pull request by kaarthiksundar**
Added exact reformulation for ````y = x*x```` using a lambda formulation.

### CODE REVIEW

**Comment by ccoffrin** [comment]
Looks suspicious to me.  @hhijazi what do you think?

**Comment by ccoffrin** [comment]
Also could you merge master into your fork.  There are some repeat commits in here, which make it hard to see what is being changed.

**Comment by kaarthiksundar** [comment]
My bad. Agreed.

-- 
Kaarthik Sundar

**Comment by hhijazi** [comment]
@ccoffrin, seems ok to me, this is a lifted convex hull formulation. @kaarthiksundar I was not able to see the lifted variable representing x*y in the commit log, maybe it's already in the code?

**Comment by ccoffrin** [comment]
This morning we figured out that the quadratic lower bound is missing.  Compare to this, https://github.com/lanl-ansi/PowerModels.jl/blob/master/src/core/relaxation_scheme.jl#L70

**Pull request closed without merging**
