### PR TITLE
Updates for PowerModels v0.15

### LINKED ISSUE #77: Re-work how solutions are reported
See if this can be simplified and if the the generic per-unit / mixed-units functions can be applied.

### LINKED ISSUE #405: Simplify MultiConductorValue Functions
For MultiConductorValues explore dropping overloaded functions like `+` in favor of dispatched versions `.+`.

### LINKED ISSUE #566: Allow add_setpoint to post a subset of variables
i.e. provide a list of damaged generators to `add_setpoint_gen_status!(...)` and only add this subset of generator variable values.

This can prevent attempting to index a variable that may not exist for all ids.

### LINKED ISSUE #575: Matrix Branch Shunts
Consider making branch shunts have the same matrix semantics as branch impedances.  E.g. see https://github.com/lanl-ansi/PowerModels.jl/pull/574.

### LINKED ISSUE #627: Proposal for more flexible result dictionaries
Formulations currently return different variable sets. E.g. SOC/SDP relaxations don't return voltage angles whereas ACP/ACR/ACT do. This was noted in https://github.com/lanl-ansi/PowerModels.jl/issues/6. 

Nevertheless, if the result of a SOC/SDP relaxation formulation satisfies its exactness guarantees, you can uniquely recover the voltage angles. On the other hand, if the relaxation is not exact, but you want to explore the result, it is currently hard to inspect the optimised values of *all* variables (e.g. wr and wi are not returned). 

Some observations
- ACP, ACR and ACT all return polar voltages
- To derive branch current, you actually want rectangular voltages
- To post-process from variable spaces P+jQ, W_i=U_i(U_i)* (e.g. includes common BFM and BIM forms) you need to know the reference bus and its reference angle (matpower assumes this is 0, but OpenDSS does not)

There is a use case for utilities to simplify conversion between variable spaces for formulations that are, or can be exact. I see 3 forms to standardize conversion utilities on
1. rectangular current and rectangular voltage
2. rectangular power and rectangular voltage
3. rectangular power and rectangular lifted voltage _+ reference bus angle(s)_
Alternatively, forms 1 and 2 can be defined with polar voltages (it adds a few redundant steps to sequential conversions, e.g. 3->1). 

Conversion between 1 and 2, and from 2 to 3 can be done node branch by branch/node by node in any order, i.e. it could be integrated in `solution_builder`. However from 3 to 2 you need to start from reference bus(es) and progress from there (order matters). This isn't easily integrated in `solution_builder`.

A mapping to existing formulations is
1. IVR
2. ACP, ACR, ACT, QC
3. SOCWR, SOCBF, SDPWRM, (QC?)

I see use cases for the following
- adding an option where each formulation returns _all_ of its variables
- by default a formulation returns the variables as defined in the above mapping (i.e. current situation)
- If you want to convert to another variable space, you need to call the right function yourself on a result dict. 

To do such conversion using only a result dict, you need a few things which currently are not stored in the result dict:
- from and to bus for each branch
- (list of) reference bus(es) and the(ir) angle(s)

I can spend a bit of time on this in the coming weeks, but I'm keen to get your thoughts before doing a lot of work.

### LINKED ISSUE #648: _make_multiconductor! still has vector shunts instead of square matrices
_make_multiconductor! still has vector shunts, whereas PowerModelsDistribution switched it data model to matrix shunts. I reckon this should be brought into sync with the actual PMD datamodel?

### LINKED ISSUE #651: Standardize Setting Bounds in Variable Declarations
Initialize all variables as unbounded, and add bounds based on the status of the `bounded` flag.

### PR DESCRIPTION
**Pull request by ccoffrin**
closes #77, closes #405, closes #566, closes #575, closes #627, closes #648, closes #651

### CODE REVIEW

**Comment by ccoffrin** [comment]
FYI @frederikgeth, @sanderclaeys, @pseudocubic, release is on its way.

**Comment by jd-lara** [comment]
@claytonbarrows

**Comment by ccoffrin** [comment]
@jd-lara, @claytonpbarrows, if you would like a hand updating your connector model I am happy to help.  At that level in the API, I _think_ the update will be fairly quick and painless.

**Comment by frederikgeth** [comment]
solid effort, thanks!

**Comment by ccoffrin** [comment]
#77 was a long time coming and well overdue.  Thank for the motivation to make it happen.

**Pull request merged**
