### PR TITLE
Support for Matlab runs

### PR DESCRIPTION
**Pull request by rb004f**
Adjusted the matpower export to protect from NaN values and run in matpower

### CODE REVIEW

**Comment by ccoffrin** [comment]
Instead of this pattern, `dict["key"] != NaN ? dict["key"] : 0` what do you think about adding a function like this?
```
function get_default(dict, key, default=0.0)
if haskey(dict, key) && dict[key] != NaN
return dict[key]
end
return default
end
```

**Comment by rb004f** [comment]
Sure.  This will also cover the (haskey(bus,"lam_q") ? bus["lam_q"] : "") cases we have in there.

**Comment by rb004f** [comment]
Yes, the issue with NaN's arose from Matpower, not matlab

**Comment by rb004f** [comment]
@ccoffrin your suggestions have been applied

**Comment by ccoffrin** [comment]
Looks good.  Thanks!

**Pull request merged**
