### PR TITLE
Initial draft of documentation

### PR DESCRIPTION
**Pull request by yeesian**
I'll take a first stab towards auto-generated docs using `Documenter.jl` (issue #12).

See the [Hosting Documentation](https://juliadocs.github.io/Documenter.jl/stable/man/hosting.html#Hosting-Documentation-1) section for details regarding how you should go about setting this up correctly.

### CODE REVIEW

**Comment by ccoffrin** [comment]
I have been holding back on comprehensive documentation becouse it significantly increases the time required for code maintenance.  But if you are open to maintaining it, I will consider merging this.

Help me understand how Documenter.jl works.  Can it auto generate some parts of the md files from docs strings that are in the code?  Doc strings are my preferred documentation method becouse its hard to ignore maintenance of them.

**Comment by yeesian** [comment]
> I have been holding back on comprehensive documentation because it significantly increases the time required for code maintenance. But if you are open to maintaining it, I will consider merging this.

I'm afraid I don't really know that much about power models, and have been documenting things as I go through the codebase in my free time. If the design/abstractions are in a relatively stable state, I'm open to help maintain it.

> Help me understand how Documenter.jl works. Can it auto generate some parts of the md files from docs strings that are in the code?

I might have been doing it wrong, but yes: https://juliadocs.github.io/Documenter.jl/stable/man/syntax.html#@docs-block-1

**Comment by ccoffrin** [comment]
No worries.  It is actually advantageous to have a novice user write the documentation becouse they understand what is confusing to new comers.

At this point I think the abstraction layers are fairly solid.  I am planning on changing the names of things fairly soon, but if the docs are generated from the code this will not be a significant overhead.

After a quick look around, I did not find that many Julia packages that are using the autodoc feature to extract documentation from doc strings.  I did find this one, which you can use as an example.

https://github.com/BenLauwens/SimJulia.jl

Have a look at,
https://benlauwens.github.io/SimJulia.jl/latest/api.html
https://raw.githubusercontent.com/BenLauwens/SimJulia.jl/master/docs/src/api.md

**Comment by yeesian** [comment]
Thanks for the pointers! This PR is now ready for review.

**Comment by ccoffrin** [comment]
I have reviewed this version.  It's looking pretty good!  Building locally I was not able to verify that the autodocs are working, but that is probably becouse we don't have any doc strings yet.  :-)  Here a few finishing touches,

- A link to the data format should be called out in the Home or Getting Started sections.  I get many questions about this, so we should help people find that page.
- The DATA.md can be removed from the root of the repo.
- The github README.md should be tidied up so that there is less replication with the docs and to call out the docs for detailed information.

My feeling is that CHANGELOG.md should also stay in the root of the repo, becouse this is more for developers than users.  Do you agree?

**Comment by yeesian** [comment]
Yup, I agree with all of your review comments, and have addressed them in the latest round of commits.

**Comment by ccoffrin** [comment]
Looks reasonable to me.  Strange the build is suddenly  failing on linux v0.5.1.

**Comment by yeesian** [comment]
I'm not sure why there's a dependency on MacroTools.jl. Try restarting the build and see?

**Comment by ccoffrin** [comment]
I just tested on the previously working master build and it has the same issue.  This issue is most likely upstream of PowerModels, so I am going to merge this.  Thanks!

**Comment by ccoffrin** [comment]
@yeesian, docs are now building with Travis and live at https://lanl-ansi.github.io/PowerModels.jl/latest/

Thanks for the contribution.

**Comment by yeesian** [comment]
Nice! 👍

Sorry I [bungled the `repo` url in deploydocs](https://github.com/lanl-ansi/PowerModels.jl/commit/c7dd8aa1b25e3070769105fe543f7ba69665f70b).

**Comment by ccoffrin** [comment]
No worries, it seems impossible to it test without pushing to Travis.

**Pull request merged**
