### PR TITLE
Switches

### PR DESCRIPTION
**Pull request by ccoffrin**
@frederikgeth, @rb004f, @pseudocubic a proposal for adding switch components to the data model.  If there are not major objections I'll add a few more formulations and then merge.

Core features of the component features are discussed here, https://github.com/lanl-ansi/PowerModels.jl/issues/339.

### CODE REVIEW

**Comment by pseudocubic** [comment]
LGTM +1

**Comment by ccoffrin** [comment]
Consider adding a node-breaker OTS example model and formulation.

**Comment by frederikgeth** [comment]
The thermal limit property suggest P^2 + Q^2 <= (thermal rating)^2, but this isn't part of the switch model. I don't feel this constraint is needed though, and box constraints should suffice for almost all use cases. 

LGTM+1

**Comment by ccoffrin** [comment]
@frederikgeth, you make a good point that the limit is not explicit in formulations and it should be.  

I agree that box constraints would be sufficient for our purpose but I failed to come up with a physical interpretation for them, thermal/current on the other hand has a well defined physical semantics that is intuitive, for me at least.  thermal/current limits also have the advantage that the user only needs to provide 1 number, rather than 4 in box bounds case.

Another option is to remove the limits from the Matpower model and use some pre-processing to compute reasonable values internally.  But I think it's better to ask the user to provide a resonable limit, even if it is quite large.  As I understand it there will always be a protection setting or a desired max loading that can motivate the need for such a limit.

**Comment by ccoffrin** [comment]
@frederikgeth, I am going to merge this so that I can integrate the updates into the v13-rc, but I would still like to come to a consensus on the finer points of the model before tagging the next v12 release.

**Comment by ccoffrin** [comment]
Closes #339.

**Pull request merged**
