### PR TITLE
Adding Support for dclinecost Data

### PR DESCRIPTION
**Pull request by ccoffrin**
This PR includes,
- Adding support for `dclinecost` data in Matpower files
- requiring that `dclinecost` data be quadratic functions for computation (similar to `gencost`)
- updating `case5_dc.m` to have a quadratic cost function
- merging `case3_dc.m` into `case3.m`, so that less test networks are required
- fixed a bug for how constant and linear cost functions were converted into quadratic

### CODE REVIEW

**Comment by ccoffrin** [comment]
@frederikgeth, @hakanergun any thoughts on this?

**Comment by ccoffrin** [comment]
@rb004f in this PR we are going to change the branch flow parameter names so that they match the Matpower data spec.  The change is from `p_from, q_from, p_to, q_to` to `pf, qf, pt, qt`.  Let me know if this will cause any significant issues for you.

**Comment by ccoffrin** [comment]
Ok, going to merge this.  @frederikgeth, @hakanergun if you have any comments/concerns we can address in another PR.

**Comment by rb004f** [comment]
No significant issues for me

**Pull request merged**
