### PR TITLE
Objective Function Improvements

### LINKED ISSUE #451: BoundsError with v0.9
Just upgraded PowerModels from v0.8.8 => v0.9.2 which seems to have introduced a bug:

```
Got an exception of type BoundsError outside of a @test
  BoundsError: attempt to access 2-element Array{Float64,1} at index [3]
  Stacktrace:
   [1] getindex(::Array{Float64,1}, ::Int64) at ./array.jl:549
   [2] macro expansion at /Users/nicoleepp/.julia/v0.6/JuMP/src/parseExpr_staged.jl:508 [inlined]
   [3] macro expansion at /Users/nicoleepp/.julia/v0.6/JuMP/src/macros.jl:859 [inlined]
   [4] _objective_min_polynomial_fuel_cost_quadratic(::PowerModels.GenericPowerModel{PowerModels.DCPlosslessForm}) at /Users/nicoleepp/.julia/v0.6/PowerModels/src/core/objective.jl:140
   [5] objective_min_polynomial_fuel_cost(::PowerModels.GenericPowerModel{PowerModels.DCPlosslessForm}) at /Users/nicoleepp/.julia/v0.6/PowerModels/src/core/objective.jl:108
   [6] objective_min_fuel_cost(::PowerModels.GenericPowerModel{PowerModels.DCPlosslessForm}) at /Users/nicoleepp/.julia/v0.6/PowerModels/src/core/objective.jl:55
   [7] post_opf(::PowerModels.GenericPowerModel{PowerModels.DCPlosslessForm}) at /Users/nicoleepp/.julia/v0.6/PowerModels/src/prob/opf.jl:25
   [8] #build_generic_model#163(::Bool, ::Bool, ::Array{Any,1}, ::Function, ::Dict{String,Any}, ::Type{T} where T, ::PowerModels.#post_opf) at /Users/nicoleepp/.julia/v0.6/PowerModels/src/core/base.jl:225
   [9] (::PowerModels.#kw##build_generic_model)(::Array{Any,1}, ::PowerModels.#build_generic_model, ::Dict{String,Any}, ::Type{T} where T, ::Function) at ./<missing>:0
   [10] #run_generic_model#161(::Function, ::Array{Any,1}, ::Function, ::Dict{String,Any}, ::Type{T} where T, ::Ipopt.IpoptSolver, ::Function) at /Users/nicoleepp/.julia/v0.6/PowerModels/src/core/base.jl:195
   [11] (::PowerModels.#kw##run_generic_model)(::Array{Any,1}, ::PowerModels.#run_generic_model, ::Dict{String,Any}, ::Type{T} where T, ::Ipopt.IpoptSolver, ::Function) at ./<missing>:0
   [12] #run_opf#605 at /Users/nicoleepp/.julia/v0.6/PowerModels/src/prob/opf.jl:15 [inlined]
   [13] (::PowerModels.#kw##run_opf)(::Array{Any,1}, ::PowerModels.#run_opf, ::Dict{String,Any}, ::Type{T} where T, ::Ipopt.IpoptSolver) at ./<missing>:0
   [14] #run_dc_opf#604 at /Users/nicoleepp/.julia/v0.6/PowerModels/src/prob/opf.jl:10 [inlined]
   [15] (::PowerModels.#kw##run_dc_opf)(::Array{Any,1}, ::PowerModels.#run_dc_opf, ::Dict{String,Any}, ::Ipopt.IpoptSolver) at ./<missing>:0
```

Same bug appears using v0.9.0 as well

### PR DESCRIPTION
**Pull request by ccoffrin**
Adds support for heterogeneous cost functions and improves performance and reliability.

Adds support for higher order polynomials.

Closes #451 

CC @nicoleepp

### CODE REVIEW

**Comment by hakanergun** [comment]
Hi, 

I was just wondering: if I have generators with zero costs (for instance if I want to use some slack or model renewables which have preference) I run into an error, because the gen["cost"] becomes an empty float. Is there any other setting/way to use such generators? Otherwise I have to assign to them little values.

**Comment by ccoffrin** [comment]
You should be able to pad with zeros rather than small values.  It sounds like a bug to me.  Can you provide a small example?  This functionality is currently tested here,

https://github.com/lanl-ansi/PowerModels.jl/blob/master/test/opf-obj.jl

And seems to be working.

**Comment by hakanergun** [comment]
The issue was on my side. I was testing a slightly different objective function formulation based on the powermodels.jl one. I must have missed the _objective_min_gen_polynomial_fuel_cost_linquad(pm::GenericPowerModel) function, which solves the issue of having different number of coefficients for the costs if generator.

**Comment by ccoffrin** [comment]
Great.  Glad to hear it!

**Pull request merged**
