### PR TITLE
Storage Component Updates

### PR DESCRIPTION
**Pull request by ccoffrin**
@frederikgeth, working on the updates we have discussed.  Please review.

As I understand the most important point to update will be to add reactive standing losses.  What do you recomend calling these?  `p_standby_loss`, `q_standby_loss`?

CC @noahrhodes, FYI this may be of interest to you.

### CODE REVIEW

**Comment by frederikgeth** [comment]
I would rename standby to something more abstract, otherwise it is confusing to model EVs or thermal storage, or run-of-river pumped hydro. I was thinking of Pext for external? or Pother?

This parameter is a time series in case of multi-period forms. We'll need a second time series to indicate the inverter/converter status as well. E.g. the energy buffer can discharge while an EV is driving (Pext forces discharge), but it can't charge while driving (e.g. converter status = 0)

**Comment by ccoffrin** [comment]
How about `p_loss`, `q_loss`, fairly generic and not prescriptive?

**Comment by frederikgeth** [comment]
I can live with that name (although the 'loss' is allowed to go negative, e.g. when water naturally flows in into the upper reservoir of a pumped hydro plant, the energy stored increases, independently of the operation of the pump/turbine).

**Comment by ccoffrin** [comment]
negative loss is fine by me as long as it has a reasonable motivation like you mention.  I'll work to that unless we think of something better in the next week or so.

**Comment by ccoffrin** [comment]
Agreed this is nominally good.  Some revisions still may come before the final release.

**Pull request merged**
