### PR TITLE
matrix shunts

### PR DESCRIPTION
**Pull request by sanderclaeys**
This change will be needed to not break the existing unit tests in PMD once we move to matrix branch shunts.

### CODE REVIEW

**Comment by pseudocubic** [comment]
@sanderclaeys be sure to check the math operations in multiconductor.jl and update any tests. I believe that some of the tests that involve MultiConductorVector math will need to be updated to use different fields because they were probably using `g_to` or the like from branches. We still want to test MultiConductorVectors though, so a different field should probably be chosen in those cases.

**Comment by ccoffrin** [comment]
Agreed, other sections of the code and the tests most likely need to be updated.  This will be a breaking change so we will merge after the next v0.12 release.

**Comment by sanderclaeys** [comment]
Maybe this should not even be part of PowerModels after all. It would also require for example rewriting constraint_voltage_angle_difference.

Instead, I will create a new make_multiconductor! method at PMD level, which adjusts the matrix shunts after the call to PM. This should be enough to fix the broken unit tests.

**Comment by ccoffrin** [comment]
Sounds like a good plan to me.  We can revisit this in due course, especially during https://github.com/lanl-ansi/PowerModels.jl/issues/568.

**Pull request closed without merging**
