### PR TITLE
Remove unused functions in solution.jl

### PR DESCRIPTION
**Pull request by frederikgeth**
Fixes https://github.com/lanl-ansi/PowerModels.jl/issues/637

### CODE REVIEW

**Comment by ccoffrin** [comment]
We need to add tests as well, to make sure the same bug does not resurface.

**Comment by ccoffrin** [comment]
Also change log description should be slightly longer.

**Comment by frederikgeth** [comment]
I added tests added for power flow result dicts (only OPF was tested).

The following functions are now removed as they were seemingly unused (that's why the tests didn't catch it) because they were superseded by new ones:
- get_solution -> solution_opf!
- add_generator_power_setpoint -> add_setpoint_generator_power!
- add_storage_setpoint -> add_setpoint_storage!
- add_branch_flow_setpoint -> add_setpoint_branch_flow!
- add_dcline_flow_setpoint -> add_setpoint_dcline_flow!
a merge error probably caused this bug? Note that this removal is potentially breaking.

ready for another inspection once Travis passes.

**Comment by ccoffrin** [comment]
So it looks like the primary issue here was that there was some dead code that should have been removed in v0.12, but it was not.  Is that a fair assessment?  If so it's not a bug in the implementation.

**Comment by frederikgeth** [comment]
Indeed. Other than updating the changelog and #637, is there anything more to address?

**Comment by ccoffrin** [comment]
Nope, looks good.  I am just debating myself if we should treat this as a breaking bug fix (i.e. v0.13) or if we should put it in the next breaking release (i.e. v0.14).  I am leaning to including in v0.13.

**Comment by frederikgeth** [comment]
Updated changelog. Ready to merge if travis passes

**Comment by ccoffrin** [comment]
I will merge after getting v0.13.1 tagged.

**Pull request merged**
