### PR TITLE
PSSE transformer Zeq scaling, winding and nominal voltage import all fix

### PR DESCRIPTION
**Pull request by KSepetanc**
Proposition to solve: PSSE import - transformer impedance scaling and winding voltage #629

I haven't done side by side tests for three winding transformers as my network didn't have any.
However, for two winding transformers I can confirm it was necessary to scale Z with |t2|^2 to get the same results as PSSE. This is described in PSSE manual cited in the issue thread.

Winding voltage and nominal voltage are required for manual implementation of tap changers and should be loaded when import all is specified.

### CODE REVIEW

**Comment by ccoffrin** [comment]
Thanks for the PR.  The changes do impact the unit tests, so this a significant change.  We should verify that the change improves consistency with respect to PSSE.  Can you do a side-by-side comparison on these two cases,
- "5-bus case", `data/pti/case5.raw` (unchanged control)
- "5-bus with asymmetric line charge case", `data/pti/case5_alc.raw` (changed breaking test)

If a power flow solve for these are consistent with PSSE, then the unit tests need to be updated to reflect the revised model.

**Comment by KSepetanc** [comment]
I have temporary reverted to original PowerModels code regrading the Input all.

I have adapted the code to account for transformer["CW"] flag so it should work now.

I have done side by side tests on proposed networks:
modified secondary tap as the original had |t2|=1 and recomputed in PSSE;
fixed all voltage magnitudes and angles to the result of PSSE calculation and added on every bus virtual unlimited generator (P and Q as free variables) so the model is feasible (and removed P^2+Q^2<=S^2 equations);
all existing generators are also producing fixed quantities as calculated by PSSE;
virtual production is zero on forked PowerModels and nonzero around transformers with original.

This exercise confirms the fix for 2 winding transformers. I have also tested with another CW flag.
However, the networks do not contain 3 winding transformers so I can not confirm that case.

Regarding the import all, I would like to get tap1,2 and 3 which I basically calculated in the steps to fix Zeq scaling. Tap1,2 and 3 are generally not e.g. transformer["WINDV2"] as I thought initially.

How to export these calculated scaling values (tap1,2,3)?

Please note there is free PSSE Xplore which is basically normal PSSE for up-to 50 buses.

**Comment by KSepetanc** [comment]
I tested side by side 3 winding transformers in PSSE and PowerModels on three_winding_test.raw.

Original PowerModels matches Z calculations in PSSE. This might be simplification on PSSE side (it seems that it doesn't do scalings as it does for two winding transformers).

However, I found another PowerModels bug in that test case. It does cause wrong power flows as a result:
Star bus is marked as inactive if primary winding is inactive;
This removes connecting active branches (secondary and tertiary) and thus the error;
Warning message occurs: 
[warn | PowerModels]: active branch 12 is connected to inactive bus 10004
[warn | PowerModels]: active branch 11 is connected to inactive bus 10004

Second error is that all star buses are always in the set of buses. This shouldn't happen when all windings are inactive.

I don't think I could tamper with bus notations for PR and it should be a separate PR.

Remained to be fixed as part of this PR:
Exporting data. I basically need |t2|. |Tap|=|t1|/|t2| and |t1| range is usually specified, i.e. 20 steps from 0.9 to 1.1 or similar. |t2| is needed to correctly implement OLTC.
Do you have suggestions how to deal with this problem?

Another question is how does PowerModels compute, and it does compute, star bus voltage magnitude and angle? (Vm and Va)

**Comment by KSepetanc** [comment]
@ccoffrin can you help with this? Also, why did codecov fail? What does it do?

**Comment by ccoffrin** [comment]
@KSepetanc, sorry for the delay!  This is not a blocking issue, but it is useful information.  This means that slightly less lines of code are covered by the tests than before.  This often happens when adding some lines of new code.  In this case it indicates that we should add a test network where these new winding computations are utilized.

Concerning the status issue, that should be addressed on the master branch.  You will want to sync your fork.

If you are happy with the constant calculations in this PR I am happy to merge it.  It seems like it does not impact the current tests, which is good.

As I understand it, the last remaining outstanding point is be able to get at the `WINDV` values when using `import_all=true`, I can take care of that on master for you.

Does that sound reasonable?

**Comment by KSepetanc** [comment]
HI @ccoffrin . The last commit, a few moments ago just removes one empty line to make the code nicer.

Data needed to calculate |t2| of transformer which is needed for OLTC:
"CW"
"WINDV"
"NOMV"

It also needs the following data which is already available:
bus base_kv
source_id - "winding" (to know if it is 2 winding or 3 winding)

It is appreciated very much if you can fix this output data.

Summary regarding the star node bugs:
1) Star bus is marked as inactive if primary winding is inactive (should be all 3 inactive to be marked inactive);
2) All star buses are always in the set of buses regardless of activity status.

Star node bugs will change some test results. (at least three_winding_test.raw)

I an fine with pulling in this commit. I have checked side by side with PSSE.
2 winding calculations are now fixed. 3 winding calculations were correct in original master PM.

**Comment by KSepetanc** [comment]
When CW=3 then NOMV# is needed as well since for that CW WINDV is defined in p.u. with base equal to NOMV. So, the |t#|=windv#*(nomv#/bus_base_kv).

Can you export that as well? Other things work and this is the last outstanding thing.

**Comment by ccoffrin** [comment]
`nomv` on import all added to master.

**Comment by KSepetanc** [comment]
It works!
Should be ready for a merge.
Thanks!

**Pull request merged**
